name: Push to Docker Hub on MetaTrader5 release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history

      - name: Check if folder has changed
        id: folder-changed
        run: |
          if git diff --quiet HEAD^ HEAD -- /MT5; then
            echo "::set-output name=changed::false"
          else
            echo "::set-output name=changed::true"
          fi

      - name: Build and push Docker image
        if: ${{ steps.folder-changed.outputs.changed == 'true' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t MetaTrader5 -f /MT5/Dockerfile.MetaTrader5 .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag MetaTrader5 MetaTrader5:latest
          docker push MetaTrader5:latest
